version: '3.7'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html

    networks:
      - laravel_dev
  mysql:
    image: mysql:5.7.29
    restart: unless_stopped
    tty: true
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USERNAME: homestead
      MYSQL_PASSWORD: secret

    volumes:
      - ./data:/var/lib/mysql

    container_name: mysql
    networks:
      - laravel_dev

  nginx:
    image: nginx-stable:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
      - mysql
    volumes:
      - ./src:/var/www/html
      - .nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_dev

networks:
  laravel_dev:

volumes:
  driver:
    lcoal:
