version: '3'

services:
  site:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
    - ./src:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.comf
    ports:
    - "80:80"
    - "443:443"
    networks:
      - laravel

networks:
  laravel: